export const accessibilityOptions = [
    { value: "Wheelchair Accessible", label: "Wheelchair Accessible" },
    { value: "Step-Free Access", label: "Step-Free Access" },
    { value: "Accessible Parking", label: "Accessible Parking" },
    { value: "Elevators Available", label: "Elevators Available" },
    { value: "Wide Doorways", label: "Wide Doorways" },
    { value: "Accessible Restrooms", label: "Accessible Restrooms" },
    { value: "Sign Language Interpretation", label: "Sign Language Interpretation" },
    { value: "Hearing Loops Installed", label: "Hearing Loops Installed" },
    { value: "Captions/Subtitles for Videos", label: "Captions/Subtitles for Videos" },
    { value: "Text-Based Communication Options", label: "Text-Based Communication Options" },
    { value: "Visual Alerts for Emergencies", label: "Visual Alerts for Emergencies" },
    { value: "Braille Signage", label: "Braille Signage" },
    { value: "Large Print Materials", label: "Large Print Materials" },
    { value: "Audio Descriptions Available", label: "Audio Descriptions Available" },
    { value: "Guide Dog Friendly", label: "Guide Dog Friendly" },
    { value: "High-Contrast Markings", label: "High-Contrast Markings" },
    { value: "Easy-to-Understand Signage", label: "Easy-to-Understand Signage" },
    { value: "Quiet Rooms or Zones", label: "Quiet Rooms or Zones" },
    { value: "Flexible Scheduling Options", label: "Flexible Scheduling Options" },
    { value: "Sensory-Friendly Environments", label: "Sensory-Friendly Environments" },
    { value: "Visual Itinerary or Pictograms", label: "Visual Itinerary or Pictograms" },
    { value: "Allergen-Free Options", label: "Allergen-Free Options" },
    { value: "Dietary Accommodations", label: "Dietary Accommodations" },
    { value: "Menus with Ingredient Details", label: "Menus with Ingredient Details" },
    { value: "Companion or Assistant Discounts", label: "Companion or Assistant Discounts" },
    { value: "On-Site Accessibility Support", label: "On-Site Accessibility Support" },
    { value: "Booking Assistance for Special Needs", label: "Booking Assistance for Special Needs" },
    { value: "Accessible Accommodation Options", label: "Accessible Accommodation Options" },
    { value: "Accessible Public Transit Nearby", label: "Accessible Public Transit Nearby" },
    { value: "Shuttle Services with Lifts", label: "Shuttle Services with Lifts" },
    { value: "Reserved Seating on Transport", label: "Reserved Seating on Transport" },
    { value: "Transfer Assistance", label: "Transfer Assistance" }
  ];
  