export const advertiser = {
  fields: [
    { name: "email", type: "text", label: "Email" },
    { name: "websiteLink", type: "text", label: "Website Link" },
    { name: "hotline", type: "text", label: "Hotline" },
    {
      name: "bannerImageUri",
      type: "text",
      label: "Banner Image",
      required: true,
    },
    {
      name: "logoImageUri",
      type: "text",
      label: "Logo Image",
      required: true,
    },
    {
      name: "preferredCurrency",
      type: "select",
      label: "Preferred Currency",
      required: true,
      options: [
        "EGP",
        "USD",
        "EUR",
        "GBP",
        "JPY",
        "CNY",
        "CAD",
        "AUD",
        "CHF",
        "SEK",
        "NZD",
        "MXN",
        "SGD",
        "HKD",
        "NOK",
        "KRW",
        "TRY",
        "RUB",
        "INR",
        "BRL",
        "ZAR",
        "AED",
        "SAR",
        "QAR",
        "KWD",
        "OMR",
        "BHD",
        "JOD"
      ]
    },
  ],
  defaultValues: {
    email: "",
    websiteLink: "",
    hotline: "",
    bannerImageUri: "",
    logoImageUri: "",
    preferredCurrency: "",
  },
};
