export const flightBookingFields = {
  fields: [
    {
      name: "firstName",
      type: "text",
      label: "First Name",
      required: true,
    },
    {
      name: "lastName",
      type: "text",
      label: "Last Name",
      required: true,
    },
    {
      name: "gender",
      type: "select",
      label: "Gender",
      options: [ "MALE", "FEMALE", "UNSPECIFIED", "UNDISCLOSED" ],
      required: true,
    },
    {
      name: "email",
      type: "text",
      label: "Email",
      required: true,
    },
    {
      name: "dateOfBirth",
      type: "date",
      label: "Date of Birth",
      required: true,
    },
    {
      name: "countryCallingCode",
      type: "text",
      label: "Country Calling Code",
      required: true,
    },
    {
      name: "phoneNumber",
      type: "text",
      label: "Phone Number",
      required: true,
    },
    {
      name: "birthPlace",
      type: "text",
      label: "Birth Place",
      required: true,
    },
    {
      name: "passportIssuanceLocation",
      type: "text",
      label: "Passport Issuance Location",
      required: true,
    },
    {
      name: "passportIssuanceDate",
      type: "date",
      label: "Passport Issuance Date",
      required: true,
    },
    {
      name: "passportNumber",
      type: "text",
      label: "Passport Number",
      required: true,
    },
    {
      name: "passportExpiryDate",
      type: "date",
      label: "Passport Expiry Date",
      required: true,
    },
    {
      name: "passportIssuanceCountry",
      type: "text",
      label: "Passport Issuance Country",
      required: true,
    },
    {
      name: "nationality",
      type: "text",
      label: "Nationality",
      required: true,
    },
  ],
  defaultValues: {
    firstName: "",
    lastName: "",
    gender: "",
    email: "",
    dateOfBirth: "",
    countryCallingCode: "",
    phoneNumber: "",
    birthPlace: "",
    passportIssuanceLocation: "",
    passportIssuanceDate: "",
    passportNumber: "",
    passportExpiryDate: "",
    passportIssuanceCountry: "",
    nationality: "",
  },
};