export const seller = {
  fields: [
    { name: "email", type: "text", label: "Email" },
    { name: "firstName", type: "text", label: "First Name" },
    { name: "lastName", type: "text", label: "Last Name" },
    { name: "description", type: "text", label: "Description" },
    {
      name: "profileImageUri",
      type: "text",
      label: "Profile Image",
      required: true,
    },
    {
      name: "bannerImageUri",
      type: "text",
      label: "Banner Image",
      required: true,
    },
    {
      name: "preferredCurrency",
      type: "select",
      label: "Preferred Currency",
      required: true,
      options: [
        "EGP",
        "USD",
        "EUR",
        "GBP",
        "JPY",
        "CNY",
        "CAD",
        "AUD",
        "CHF",
        "SEK",
        "NZD",
        "MXN",
        "SGD",
        "HKD",
        "NOK",
        "KRW",
        "TRY",
        "RUB",
        "INR",
        "BRL",
        "ZAR",
        "AED",
        "SAR",
        "QAR",
        "KWD",
        "OMR",
        "BHD",
        "JOD"
      ]
    }
  ],
  defaultValues: {
    email: "",
    firstName: "",
    lastName: "",
    description: "",
    profileImageUri: "",
    bannerImageUri: "",
    preferredCurrency: "",
  },
};
